project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)

website:

  title: "Animal Tracking in biologia della conservazione"
  reader-mode: true
  page-navigation: true
  description: ""
  site-url: https://giulianocolosimo.github.com
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
    
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
#      - text: "Calendar"
#        href: calendar.qmd
#      - text: "Contact"
#        href: contact.qmd

  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    contents:
      - section: "Classes"
        title: "Classes"
        contents: 
          - href: ./classes/Animal tracking 25-26 - Class 1 - Introduction to movement.pdf
            text: "Class 1 - Introduction to movement"
            icon: file-pdf
          - href: ./classes/Animal tracking 25-26 - Class 2 - Spatial data.pdf
            text: "Class 2 - Spatial data"
            icon: file-pdf
          - href: ./classes/Animal tracking 25-26 - Class 3 - Species distribution.pdf
            text: "Class 3 - Species distribution"
            icon: file-pdf




    tools:
      - icon: envelope
        url: "mailto:giuliano.colosimo@protonmail.com"

  page-footer:
    left: "© Copyright 2025 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)."
    background: dark
    

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
